// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzx-Io09B7tXR2RicKH5_u6zj1X7oxBd8',
    appId: '1:568986014154:web:47bb5b5b755ddb90fc7f33',
    messagingSenderId: '568986014154',
    projectId: 'vreal0',
    authDomain: 'vreal0.firebaseapp.com',
    storageBucket: 'vreal0.appspot.com',
    measurementId: 'G-L4SZN0J2PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7XCPH9114iRsePzwKIUQ60gCPsAP8uA8',
    appId: '1:568986014154:android:cd9e23c27b9c7622fc7f33',
    messagingSenderId: '568986014154',
    projectId: 'vreal0',
    storageBucket: 'vreal0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV9jnl8TMa2hDZ5175i5EEtSKjWXUlLCM',
    appId: '1:568986014154:ios:650068df92f45470fc7f33',
    messagingSenderId: '568986014154',
    projectId: 'vreal0',
    storageBucket: 'vreal0.appspot.com',
    iosClientId: '568986014154-lohgbms4vrri9026heqoec9osij2qbu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vreal0',
  );
}
